#!/bin/sh
#
# name     : tmuxen, tmux environment made easy
# author   : Xu Xiaodong <xxdlhy@gmail.com>
# license  : GPL
# created  : 2012 Jul 01
# modified : 2012 Nov 16
#

cmd=$(which tmux) # tmux path
session=android   # session name

if [ -z $cmd ]; then
  echo "You need to install tmux."
  exit 1
fi

$cmd has -t $session 2> /dev/null

if [ $? != 0 ]; then
  $cmd new -d -n vim -s $session "vim"
  $cmd neww -n schroot -t $session "schroot bash"
  $cmd neww -n zsh -t $session "zsh"
  $cmd splitw -h -p 50 -t $session "zsh"
  $cmd selectw -t $session:0
fi

$cmd att -t $session

exit 0
